#######################################################################################################################
# (C)2022 Mihael Skarabot, private
#
# Test deployment to docker hub from github actions
#######################################################################################################################

FROM ubuntu:20.04

ENV LANG en_US.UTF-8
ENV LC_ALL en_US.UTF-8
ENV TERM linux

CMD ["/bin/bash"]